#!/bin/bash

BASE_DIR=$(cd $(dirname $0);pwd)

# Setup vim
if [ -d ~/.vim ]; then
  echo '[Error] .vim directory exists.'
#  exit 1
fi

ln -s $BASE_DIR/.vim ~/.vim

if [ -f ~/.vimrc ]; then
  echo '[Error] .vimrc file exists.'
#  exit 1
fi

ln -s $BASE_DIR/.vimrc ~/.vimrc

if [ -d $BASE_DIR/.vim/dein/repos/github.com/Shougo/dein.vim ]; then
  rm -Rf $BASE_DIR/.vim/dein/repos/github.com/Shougo/dein.vim
fi

git clone https://github.com/Shougo/dein.vim.git $BASE_DIR/.vim/dein/repos/github.com/Shougo/dein.vim

# Setup git
ln -s $BASE_DIR/.gitconfig ~/.gitconfig

# Setup Zsh
#ln -s $BASE_DIR/.zshrc ~/.zshrc

echo 'Install success.'
