[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='''
  " 隠しファイルをデフォルトで表示
  let NERDTreeShowHidden = 1

  " <Ctrl-l>: ファイルリストを開く
  nnoremap <C-l> :NERDTreeTabsToggle<CR>

  " <Ctrl-e>: NERDTreeとファイルのフォーカスを切り替える
  nnoremap <C-e> :NERDTreeFocusToggle<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
